

service: drone-co-message-broker

provider:
  name: aws
  runtime: nodejs12.x
  role: MsgBrokerServiceRole
# you can overwrite defaults here
# region: us-east-1

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

package: 
  include: # Specify the directories and files which should be included in the deployment package
  exclude: 
    - .git/**
    - node_modules/aws-sdk # so that aws-sdk and all its dependencies are ignored

functions:
  createMsgMapping:
    handler: handlers/createMsgMapping.main
    events:
      - http:
          path: mapping
          method: post
          cors: true

  createMsgContent:
    handler: handlers/createMsgContent.main
    events:
      - http:
          path: content
          method: post
          cors: true

# this is where you include raw cloud formation
resources:
  - ${file(./cloudFormation/iamRole.yml)}
  - ${file(./cloudFormation/tables.yml)}

