Resources:
  MessageContent:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      # if commented out tableName will be generated
      # TableName: MessageContent 
      AttributeDefinitions:
        - AttributeName: contentId
          AttributeType: S
      KeySchema:
        - AttributeName: contentId
          KeyType: HASH

  MessageMapping:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      # TableName: MessageMapping
      AttributeDefinitions:
        - AttributeName: recipientId
          AttributeType: S
        - AttributeName: contentId
          AttributeType: S
      KeySchema:
        - AttributeName: recipientId
          KeyType: HASH
        - AttributeName: contentId
          KeyType: RANGE